spring.mongodb.uri= mongodb+srv://rushi_kesh219:bumblebee@cluster0.5hvsu8b.mongodb.net/
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true

